### ISSUE TITLE
Interest signature is not in the name

### ISSUE THREAD

**Issue by Pesa** [named-data/StateVectorSync#2]
[Here](https://github.com/named-data/StateVectorSync/blob/33776087393f77614df469b1807bd5f436513394/Specification.md#7-interest-authentication) it is stated that "The last name component of the Sync Interest is the signature", which is not correct. The last component is a `ParametersSha256DigestComponent`.

I think you can remove that sentence and just link to the spec: https://named-data.net/doc/NDN-packet-spec/0.3/signed-interest.html

**Comment by phylib** [comment]
Hi @Pesa, thanks for reviewing the spec. Just committed the change with `#3dea2a3`.

**Comment by Pesa** [comment]
👍
