### ISSUE TITLE
Specifying TLV types

### ISSUE THREAD

**Issue by tylerliu** [named-data/StateVectorSync#9]
In C++ ndn-svs implementation, TLV type for SeqNo = 204; for Python SVS implementation, TLV type for SeqNo = 203. 

Can we have specification for TLV types needed so there are inconsistency between implementations?

https://github.com/named-data/ndn-svs/blob/master/ndn-svs/tlv.hpp
https://github.com/justincpresley/ndn-python-svs/blob/traditional/svs/tlv.py

**Comment by Pesa** [comment]
> Can we have specification for TLV types needed so there are inconsistency between implementations?

We already have it: https://named-data.github.io/StateVectorSync/Specification.html
and it says `SeqNo` has type 204.

(I don't know why 203 was skipped, but oh well...)

**Comment by tylerliu** [comment]
So Python Implementation got issues...

**Comment by pulsejet** [comment]
> (I don't know why 203 was skipped, but oh well...)

[No idea](https://github.com/named-data/StateVectorSync/commit/c2665db6b9e8ad53a5f3085243a438e4f12fe808#diff-e7e2fa8723d3a4c69e37b7668c9d2e7550513164fe1a17efaaaf4efce0d8f2e9L60-L69). It wasn't possible to create a backward compatible implementation anyway.

> So Python Implementation got issues...

I think it's using the older spec [here](https://github.com/justincpresley/ndn-python-svs/blob/15c84a39a4291e887569414b3f66ca1d07a5f1a2/src/ndn/svs/state_vector.py#L28-L38).
